/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nfdwgvykrghteajsiykm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZHdndnlrcmdodGVhanNpeWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxOTQ1NjIsImV4cCI6MjA5Mzc3MDU2Mn0.kwv6zHTm7lhGB2PFi-bKwR0ns7a-fmWZn7snJwKuzFA"